#AQUI SE CONFIGURAN LOS CONTENEDORES
services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-database
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql

  frontend:
    image: cliente:v1.0
    build:
      context: ./sgu-frontend
      args:
        API_HOST: localhost
        API_PORT: 8080
        API_BASE: /sgu-api
    container_name: sgu-frontend
    ports:
      - "3000:80"
    networks:
      - sgu-net
    depends_on:
      - database

  backend:
    image: server:1.0
    build:
      context: ./sgu-backend
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu-database
      DB_USER: root
      DB_PASS: root
    ports:
      - "8080:8080"
    networks:
      - sgu-net
    depends_on:
      - frontend

networks:
  sgu-net:
    external: true



volumes:
  sgu-volume:
    external: true